# Generated by Django 6.0.3 on 2026-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('unit', models.CharField(default='piece', verbose_name=[('l', 'Litr'), ('piece', 'Dona'), ('box', 'Quti')])),
                ('amout', models.IntegerField()),
                ('category', models.ManyToManyField(related_name='products', to='ombor.category')),
            ],
        ),
    ]
